/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as CreatorIndexRouteImport } from './routes/creator/index'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as CreatorModulesLessonsRouteImport } from './routes/creator/modules/lessons'
import { Route as CreatorCoursesOutlineRouteImport } from './routes/creator/courses/outline'
import { Route as CreatorCoursesNewRouteImport } from './routes/creator/courses/new'
import { Route as CreatorLessonsLessonIdIndexRouteImport } from './routes/creator/lessons/$lessonId/index'
import { Route as CreatorModulesModuleIdLessonsRouteImport } from './routes/creator/modules/$moduleId/lessons'
import { Route as CreatorLessonsLessonIdQuizRouteImport } from './routes/creator/lessons/$lessonId/quiz'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorIndexRoute = CreatorIndexRouteImport.update({
  id: '/creator/',
  path: '/creator/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const CreatorModulesLessonsRoute = CreatorModulesLessonsRouteImport.update({
  id: '/creator/modules/lessons',
  path: '/creator/modules/lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorCoursesOutlineRoute = CreatorCoursesOutlineRouteImport.update({
  id: '/creator/courses/outline',
  path: '/creator/courses/outline',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorCoursesNewRoute = CreatorCoursesNewRouteImport.update({
  id: '/creator/courses/new',
  path: '/creator/courses/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorLessonsLessonIdIndexRoute =
  CreatorLessonsLessonIdIndexRouteImport.update({
    id: '/creator/lessons/$lessonId/',
    path: '/creator/lessons/$lessonId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CreatorModulesModuleIdLessonsRoute =
  CreatorModulesModuleIdLessonsRouteImport.update({
    id: '/creator/modules/$moduleId/lessons',
    path: '/creator/modules/$moduleId/lessons',
    getParentRoute: () => rootRouteImport,
  } as any)
const CreatorLessonsLessonIdQuizRoute =
  CreatorLessonsLessonIdQuizRouteImport.update({
    id: '/creator/lessons/$lessonId/quiz',
    path: '/creator/lessons/$lessonId/quiz',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/items': typeof LayoutItemsRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/creator': typeof CreatorIndexRoute
  '/creator/courses/new': typeof CreatorCoursesNewRoute
  '/creator/courses/outline': typeof CreatorCoursesOutlineRoute
  '/creator/modules/lessons': typeof CreatorModulesLessonsRoute
  '/creator/lessons/$lessonId/quiz': typeof CreatorLessonsLessonIdQuizRoute
  '/creator/modules/$moduleId/lessons': typeof CreatorModulesModuleIdLessonsRoute
  '/creator/lessons/$lessonId': typeof CreatorLessonsLessonIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/items': typeof LayoutItemsRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/creator': typeof CreatorIndexRoute
  '/creator/courses/new': typeof CreatorCoursesNewRoute
  '/creator/courses/outline': typeof CreatorCoursesOutlineRoute
  '/creator/modules/lessons': typeof CreatorModulesLessonsRoute
  '/creator/lessons/$lessonId/quiz': typeof CreatorLessonsLessonIdQuizRoute
  '/creator/modules/$moduleId/lessons': typeof CreatorModulesModuleIdLessonsRoute
  '/creator/lessons/$lessonId': typeof CreatorLessonsLessonIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/creator/': typeof CreatorIndexRoute
  '/creator/courses/new': typeof CreatorCoursesNewRoute
  '/creator/courses/outline': typeof CreatorCoursesOutlineRoute
  '/creator/modules/lessons': typeof CreatorModulesLessonsRoute
  '/creator/lessons/$lessonId/quiz': typeof CreatorLessonsLessonIdQuizRoute
  '/creator/modules/$moduleId/lessons': typeof CreatorModulesModuleIdLessonsRoute
  '/creator/lessons/$lessonId/': typeof CreatorLessonsLessonIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/items'
    | '/settings'
    | '/'
    | '/creator'
    | '/creator/courses/new'
    | '/creator/courses/outline'
    | '/creator/modules/lessons'
    | '/creator/lessons/$lessonId/quiz'
    | '/creator/modules/$moduleId/lessons'
    | '/creator/lessons/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/items'
    | '/settings'
    | '/'
    | '/creator'
    | '/creator/courses/new'
    | '/creator/courses/outline'
    | '/creator/modules/lessons'
    | '/creator/lessons/$lessonId/quiz'
    | '/creator/modules/$moduleId/lessons'
    | '/creator/lessons/$lessonId'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/items'
    | '/_layout/settings'
    | '/_layout/'
    | '/creator/'
    | '/creator/courses/new'
    | '/creator/courses/outline'
    | '/creator/modules/lessons'
    | '/creator/lessons/$lessonId/quiz'
    | '/creator/modules/$moduleId/lessons'
    | '/creator/lessons/$lessonId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  CreatorIndexRoute: typeof CreatorIndexRoute
  CreatorCoursesNewRoute: typeof CreatorCoursesNewRoute
  CreatorCoursesOutlineRoute: typeof CreatorCoursesOutlineRoute
  CreatorModulesLessonsRoute: typeof CreatorModulesLessonsRoute
  CreatorLessonsLessonIdQuizRoute: typeof CreatorLessonsLessonIdQuizRoute
  CreatorModulesModuleIdLessonsRoute: typeof CreatorModulesModuleIdLessonsRoute
  CreatorLessonsLessonIdIndexRoute: typeof CreatorLessonsLessonIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/': {
      id: '/creator/'
      path: '/creator'
      fullPath: '/creator'
      preLoaderRoute: typeof CreatorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/creator/modules/lessons': {
      id: '/creator/modules/lessons'
      path: '/creator/modules/lessons'
      fullPath: '/creator/modules/lessons'
      preLoaderRoute: typeof CreatorModulesLessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/courses/outline': {
      id: '/creator/courses/outline'
      path: '/creator/courses/outline'
      fullPath: '/creator/courses/outline'
      preLoaderRoute: typeof CreatorCoursesOutlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/courses/new': {
      id: '/creator/courses/new'
      path: '/creator/courses/new'
      fullPath: '/creator/courses/new'
      preLoaderRoute: typeof CreatorCoursesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/lessons/$lessonId/': {
      id: '/creator/lessons/$lessonId/'
      path: '/creator/lessons/$lessonId'
      fullPath: '/creator/lessons/$lessonId'
      preLoaderRoute: typeof CreatorLessonsLessonIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/modules/$moduleId/lessons': {
      id: '/creator/modules/$moduleId/lessons'
      path: '/creator/modules/$moduleId/lessons'
      fullPath: '/creator/modules/$moduleId/lessons'
      preLoaderRoute: typeof CreatorModulesModuleIdLessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/lessons/$lessonId/quiz': {
      id: '/creator/lessons/$lessonId/quiz'
      path: '/creator/lessons/$lessonId/quiz'
      fullPath: '/creator/lessons/$lessonId/quiz'
      preLoaderRoute: typeof CreatorLessonsLessonIdQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  CreatorIndexRoute: CreatorIndexRoute,
  CreatorCoursesNewRoute: CreatorCoursesNewRoute,
  CreatorCoursesOutlineRoute: CreatorCoursesOutlineRoute,
  CreatorModulesLessonsRoute: CreatorModulesLessonsRoute,
  CreatorLessonsLessonIdQuizRoute: CreatorLessonsLessonIdQuizRoute,
  CreatorModulesModuleIdLessonsRoute: CreatorModulesModuleIdLessonsRoute,
  CreatorLessonsLessonIdIndexRoute: CreatorLessonsLessonIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
